spring:
    profiles:
        active: dev
    jackson:
        date-format: yyyy-MM-dd HH:mm
        time-zone: GMT+8
mybatis:
    typeAliasesPackage: cn.edu.dgut.educationalsystem.model
    mapperLocations: classpath:mapper/*.xml
pagehelper:
    helpDialect: mysql
---

spring:
    profiles: dev
    datasource:
        url: jdbc:mysql://localhost:3306/es?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
---

spring:
    profiles: dev2
    datasource:
        url: jdbc:mysql://localhost:3306/es?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: 111111
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource